# Generated by Django 3.0 on 2019-12-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('cartao', models.IntegerField()),
                ('pagamento', models.CharField(choices=[('AV', 'Pagamento à vista'), ('P2', 'Pagamento em 2x'), ('P3', 'Pagamento em 3x')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='postagem',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
